/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'takeo' at '16/10/13 14:01' with Gradle 3.1
 *
 * @author takeo, @date 16/10/13 14:01
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
